name: ⚡ Feature
description: 새로운 기능이나 변경사항이 있나요?
title: '[Feat] '
labels: ['⚡ Feature']
body:
  - type: textarea
    id: feature-description
    attributes:
      label: 📄 설명
      description: 새로운 기능에 대한 설명을 작성해 주세요.
      placeholder: 최대한 자세하게 작성!
    validations:
      required: true
  - type: textarea
    id: feature-todo
    attributes:
      label: ✅ 해야 할 일
      description: 해야 할 일에 대한 목록을 작성해 주세요.
      placeholder: 최대한 세분화하여 작성!
    validations:
      required: true
  - type: textarea
    id: feature-more
    attributes:
      label: 📝 메모
      description: 추가로 할 말이 있다면 작성해 주세요.
    validations:
      required: false
